apiVersion: v1
kind: Namespace
metadata:
  name: insurance-platform
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: claims-api
  namespace: insurance-platform
  labels:
    app: claims-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: claims-api
  template:
    metadata:
      labels:
        app: claims-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: claims-api
        image: insurance-platform/claims-api:local
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: PORT
          value: "8080"
        - name: GIN_MODE
          value: "debug"
        - name: LOG_LEVEL
          value: "debug"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: claims-api
  namespace: insurance-platform
  labels:
    app: claims-api
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: claims-api 