apiVersion: v1
kind: Service
metadata:
  name: claims-api
  namespace: insurance-platform
  labels:
    app: claims-api
    component: backend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: claims-api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: claims-api
  namespace: insurance-platform
  labels:
    app: claims-api
    component: backend
automountServiceAccountToken: true
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: claims-api
  namespace: insurance-platform
spec:
  podSelector:
    matchLabels:
      app: claims-api
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: insurance-platform
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    - namespaceSelector:
        matchLabels:
          name: monitoring
    ports:
    - protocol: TCP
      port: 8080
  egress:
  # Allow DNS resolution
  - to: []
    ports:
    - protocol: UDP
      port: 53
  # Allow database access
  - to:
    - namespaceSelector:
        matchLabels:
          name: database
    ports:
    - protocol: TCP
      port: 5432
  # Allow external HTTPS calls
  - to: []
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80 